apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tp.devops.checker: data-saver
  name: data-saver
spec:
  replicas: 1
  selector:
    matchLabels:
      tp.devops.checker: data-saver
  template:
    metadata:
      labels:
        tp.devops.checker: data-saver
    spec:
      containers:
        - env:
            # - name: DATA_RETRIEVE_EXT_PORT
            #   value: "8022"
            # - name: DATA_SAVER_EXT_PORT
            #   value: "8021"
            - name: DB_SQL_EXT
              value: sql-server-db
            - name: DB_SQL_EXT_PORT
              value: "1433"
          image: localhost:32000/data-saver:0.2
          name: data-saver
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    tp.devops.checker: data-saver
  name: data-saver
spec:
  ports:
    - name: "8021"
      port: 8021
      targetPort: 80
  selector:
    tp.devops.checker: data-saver

