# The mounted directories must have chmod -R 0777 /mydirectory before
version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server-db
    ports:
      - "11433:1433"

    volumes:
      # - /home/nxf42609/test1:/test1
      - /home/nxf42609/data/source/tpte-platform/tp-hello-devops/db-sql/db/data:/var/opt/mssql/data 
      - /home/nxf42609/data/source/tpte-platform/tp-hello-devops/db-sql/db/log:/var/opt/mssql/log 
      - /home/nxf42609/data/source/tpte-platform/tp-hello-devops/db-sql/db/secrets:/var/opt/mssql/secrets 

    environment:
      SA_PASSWORD: "MyStrongPassword123"
      ACCEPT_EULA: "Y"

networks:
  default:
    external: true
    name: tp-devops-checker
